// Code generated by templ-component-opts; DO NOT EDIT.
// This file contains functions and methods for use with Opts in templ components.
package book

import (
	"strconv"
	"time"
)

type Opt func(*Opts)

func DefaultOpts() *Opts {
	out := &Opts{Display: true}
	return out
}
func With(opts ...Opt) *Opts {
	out := DefaultOpts()
	out.With(opts...)
	return out
}
func (o *Opts) With(opts ...Opt) *Opts {
	for _, opt := range opts {
		opt(o)
	}
	return o
}

func Title(in string) Opt {
	return func(opts *Opts) {
		opts.Title = in
	}
}

func Author(in string) Opt {
	return func(opts *Opts) {
		opts.Author = in
	}
}

func Published(in time.Time) Opt {
	return func(opts *Opts) {
		opts.Published = in
	}
}

func Display(in bool) Opt {
	return func(opts *Opts) {
		opts.Display = in
	}
}

func (o *Opts) DisplayStr() string {
	return strconv.FormatBool(o.Display)
}
